"""Initial migration.

Revision ID: 0e75a1c0bd44
Revises: bf4197808366
Create Date: 2024-06-29 15:00:05.112510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e75a1c0bd44'
down_revision = 'bf4197808366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty_rating', sa.String(length=60), nullable=False))
        batch_op.drop_column('performace_rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('performace_rating', mysql.VARCHAR(length=60), nullable=False))
        batch_op.drop_column('difficulty_rating')

    # ### end Alembic commands ###
