"""empty message

Revision ID: 316d4c2ef495
Revises: 4565b75561a7
Create Date: 2025-11-24 21:26:22.181328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316d4c2ef495'
down_revision = '4565b75561a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.sql import table, column
    from sqlalchemy import String, select
    
    # Step 1: Add email column as nullable first
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=128), nullable=True))
    
    # Step 2: Update existing users with unique placeholder emails
    connection = op.get_bind()
    users_table = table('users',
        column('id', String),
        column('name', String),
        column('email', String)
    )
    
    # Get all users without emails
    users = connection.execute(select(users_table.c.id, users_table.c.name)).fetchall()
    
    for user in users:
        # Generate unique email from username
        connection.execute(
            users_table.update().where(users_table.c.id == user.id).values(
                email=f"{user.name}@flasheeta.local"
            )
        )
    
    # Step 3: Now make email NOT NULL and add unique constraint
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email', nullable=False)
        batch_op.create_unique_constraint('uq_users_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
