"""new migration.

Revision ID: 5e39844ee4a4
Revises: 8dc616fd388d
Create Date: 2024-06-30 21:12:23.378718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e39844ee4a4'
down_revision = '8dc616fd388d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.alter_column('last_review_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('next_review_date',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.alter_column('next_review_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('last_review_date',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
