"""Add ease_factor and interval to Progress model

Revision ID: 8dc616fd388d
Revises: 0e75a1c0bd44
Create Date: 2024-06-30 15:55:14.084621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc616fd388d'
down_revision = '0e75a1c0bd44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_review_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('ease_factor', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('interval', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_column('interval')
        batch_op.drop_column('ease_factor')
        batch_op.drop_column('next_review_date')

    # ### end Alembic commands ###
